### ISSUE TITLE
button Interaction

### ISSUE THREAD

**Issue by YuichiroMaki** [sotayamashita/bdash#28]
https://dribbble.com/shots/2195128-Dashboard-Module-Editor

こんなボタンが欲しい！

**Comment by sotayamashita** [comment]
この辺が参考になりますかね？

Ref:

* http://tympanus.net/Tutorials/CircularProgressButton/
* http://tympanus.net/Development/ProgressButtonStyles/

**Comment by sotayamashita** [comment]
It includes JavaScript so It is not for it.
